### ISSUE TITLE
Private signs near section changes are easily broken

### ISSUE THREAD

**Issue by c-sig** [MineInAbyss/DeeperWorld#60]
Signs that lock a specific block are able to be bypassed by just switching sections.

Reproducing the bug: 
https://b.catgirlsare.sexy/bD-wKNLv.mp4 this specific domain is a file hosting service I swear

**Expected behavior**
Sign should private blocks across sections (I guess?)

**Additional context**
Oh yeah you can do this to chests, enderchests, beds, doors, beacons, literally anything you can private

**Comment by 0ffz** [comment]
Likely because (iirc) I only implemented sign sync when interacting with containers. The code from there should be moved to whenever any sign is placed.
