### ISSUE TITLE
Getting stuck when there is no place to teleport

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/DeeperWorld#71]
Currently the movement event gets cancelled which makes it really easy for someone to get stuck and be unable to look around, etc... Previously we applied velocity away from the intersection to prevent this. Consider using this or a more elegant solution again.

**Comment by Boy0000** [comment]
Velocity was weird and didnt stop you when you used stairs. You could essentially just sneak past it.

The only issue with being stuck is when going downwards, so perhaps disabling it on the bottom TP as it doesnt really offer much
